from fondescapp._views.about_us import *
from fondescapp._views.contact import *
from fondescapp._views.courses import *
from fondescapp._views.faq import *
from fondescapp._views.home import *
from fondescapp._views.auth import *
from fondescapp._views.registration import *
from fondescapp._views.subscribe import *
from fondescapp._views.under_development import *
from fondescapp._views.metodoloji import *
from fondescapp._views.privacy_policy import *
from fondescapp._views.terms_of_use import *
from fondescapp._views.scholarships import *
