# Generated by Django 5.1.7 on 2025-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(choices=[('primary', 'Lekòl Primè'), ('secondary', 'Lekòl Segondè')], max_length=20)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_gender', models.CharField(choices=[('male', 'Gason'), ('female', 'Fi'), ('other', 'Lòt')], max_length=10)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_applying', models.CharField(choices=[('grade1', '1ye Ane'), ('grade2', '2yèm Ane'), ('grade3', '3yèm Ane'), ('grade4', '4yèm Ane'), ('grade5', '5yèm Ane'), ('grade6', '6yèm Ane'), ('grade7', '7yèm Ane'), ('grade8', '8yèm Ane'), ('grade9', '9yèm Ane'), ('grade10', '10yèm Ane'), ('grade11', '11yèm Ane'), ('grade12', '12yèm Ane')], max_length=10)),
                ('academic_year', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=10)),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('parent', 'Paran'), ('guardian', 'Responsab Legal'), ('other', 'Lòt')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('special_needs', models.BooleanField(default=False)),
                ('special_needs_details', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('how_heard', models.CharField(blank=True, choices=[('friend', 'Zanmi oswa Fanmi'), ('social_media', 'Rezo Sosyal'), ('website', 'Sit Entènèt'), ('newspaper', 'Jounal'), ('other', 'Lòt')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Enskripsyon',
                'verbose_name_plural': 'Enskripsyon yo',
            },
        ),
    ]
