# Generated by Django 5.1.7 on 2025-03-22 14:54

import django.db.models.deletion
import school_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='access_token',
            field=models.CharField(default=school_registration.models.generate_access_token, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'An Atant'), ('documents_required', 'Dokiman Obligatwa'), ('documents_received', 'Dokiman Resevwa'), ('under_review', 'Anba Revizyon'), ('interview_scheduled', 'Entèvyou Pwograme'), ('accepted', 'Aksepte'), ('rejected', 'Rejte'), ('waitlisted', 'Nan Lis Datant')], default='documents_required', max_length=30),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Sètifika Nesans'), ('report_card', 'Kanè'), ('vaccination_card', 'Kat Vaksinasyon'), ('passport_photo', 'Foto Paspò'), ('proof_of_residence', 'Prèv Rezidans'), ('recommendation_letter', 'Lèt Rekòmandasyon'), ('other', 'Lòt Dokiman')], max_length=30)),
                ('file', models.FileField(upload_to=school_registration.models.document_upload_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school_registration.enrollment')),
            ],
            options={
                'verbose_name': 'Dokiman',
                'verbose_name_plural': 'Dokiman yo',
            },
        ),
    ]
