# Generated by Django 5.1.7 on 2025-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_certificate_available_course_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
