# Generated by Django 5.1.7 on 2025-03-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
