# Generated by Django 5.1.7 on 2025-03-11 02:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Non Kou')),
                ('level', models.CharField(choices=[('high-school', 'Segondè'), ('technical', 'Teknik'), ('undergraduate', 'Lisans'), ('graduate', 'Metriz')], max_length=20, verbose_name='Nivo')),
                ('tagline', models.CharField(max_length=255, verbose_name='Slogan Kou')),
                ('duration', models.CharField(max_length=50, verbose_name='Dire')),
                ('start_dates', models.CharField(max_length=100, verbose_name='Kòmansman')),
                ('modality', models.CharField(choices=[('distance', 'A distans'), ('in-person', 'Prezansyèl'), ('hybrid', 'Ibrid')], max_length=20, verbose_name='Modalite')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Bwochi')),
                ('overview', models.TextField(verbose_name='Apèsi Kou')),
            ],
        ),
        migrations.CreateModel(
            name='CareerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, verbose_name='Valè')),
                ('label', models.CharField(max_length=100, verbose_name='Etikèt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_stats', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tit')),
                ('description', models.TextField(verbose_name='Deskripsyon')),
                ('examples', models.CharField(max_length=255, verbose_name='Egzanp')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_opportunities', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('basic', 'Kondisyon Debaz'), ('document', 'Dokiman Obligatwa')], max_length=20, verbose_name='Tip Kondisyon')),
                ('description', models.CharField(max_length=255, verbose_name='Deskripsyon')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirements', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveIntegerField(verbose_name='Ane')),
                ('title', models.CharField(default='Premye Ane', max_length=50, verbose_name='Tit Ane')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_years', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Non')),
                ('title', models.CharField(max_length=100, verbose_name='Tit')),
                ('bio', models.TextField(verbose_name='Biyografi')),
                ('photo', models.ImageField(upload_to='faculty/', verbose_name='Foto')),
                ('specialties', models.CharField(max_length=255, verbose_name='Espesyalite')),
                ('course', models.ManyToManyField(related_name='faculty_members', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tit')),
                ('description', models.TextField(verbose_name='Deskripsyon')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_aids', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Objektif Aprantisaj')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Deskripsyon')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField(choices=[(1, 'Premye Semès'), (2, 'Dezyèm Semès')], verbose_name='Semès')),
                ('curriculum_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='fondescapp.curriculumyear')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Non Matyè')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='fondescapp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefòn')),
                ('birth_date', models.DateField(verbose_name='Dat Nesans')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Gason'), ('female', 'Fi'), ('other', 'Lòt')], max_length=10, null=True, verbose_name='Sèks')),
                ('address', models.CharField(max_length=255, verbose_name='Adrès')),
                ('city', models.CharField(max_length=100, verbose_name='Vil')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kòd Postal')),
                ('is_candidate', models.BooleanField(default=True, verbose_name='Kandidan')),
                ('education_level', models.CharField(blank=True, choices=[('Elementary-i', 'Elemantè I (1ª a 5è)'), ('elementary-ii', 'Elemantè II (6è a 9è)'), ('high-school', 'Segondè'), ('technical', 'Teknik'), ('undergraduate', 'Lisans'), ('graduate', 'Metriz'), ('doctorate', 'Doktè')], max_length=100, null=True, verbose_name='Nivèl Enseman')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MethodPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('full', 'Peman Konplè'), ('installment', 'Peman an Vèsman')], default='full', max_length=20, verbose_name='Opsyon Peman')),
                ('payment_method', models.CharField(choices=[('card', 'Kat Kredi/Debi'), ('bank', 'Transfè Bank'), ('mobile', 'Peman Mobil (MonCash)')], max_length=20, verbose_name='Metòd Peman')),
                ('card_number', models.CharField(blank=True, max_length=19, null=True, verbose_name='Nimewo Kat')),
                ('card_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Non sou Kat')),
                ('card_expiry', models.CharField(blank=True, max_length=5, null=True, verbose_name='Dat Ekspirasyon')),
                ('card_cvv', models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV')),
                ('bank_receipt', models.FileField(blank=True, null=True, upload_to='payments/bank_receipts/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Resi Transfè')),
                ('mobile_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kòd Konfimasyon')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Tèm Aksepte')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fondescapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.FileField(upload_to='documents/id/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Dokiman Idantite')),
                ('diploma', models.FileField(upload_to='documents/diplomas/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Diplòm')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='documents/transcripts/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Relve Nòt')),
                ('photo', models.FileField(upload_to='documents/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Foto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fondescapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Kontni')),
                ('author_name', models.CharField(max_length=100, verbose_name='Non Otè')),
                ('author_title', models.CharField(max_length=100, verbose_name='Tit Otè')),
                ('author_photo', models.ImageField(upload_to='testimonials/', verbose_name='Foto Otè')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='fondescapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Deskripsyon')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montan (HTG)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_fees', to='fondescapp.course')),
            ],
        ),
    ]
