# Generated by Django 5.1.7 on 2025-03-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondescapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('subject', models.CharField(choices=[('general', 'General Information'), ('admissions', 'Admissions'), ('courses', 'Course Information'), ('technical', 'Technical Support'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('privacy_agree', models.BooleanField(default=False, verbose_name='Privacy Agreement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Is Replied')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
